# Extra env variables
# Note: You must relaunch Hyprland after changing envs (use Super+Esc, then Relaunch)
# env = MY_GLOBAL_ENV,setting
windowrule = opacity 1.0 1.0, match:class .*

# Configurations
exec-once = gsettings set org.gnome.desktop.interface gtk-theme "Adwaita-dark"  # for GTK3 apps
exec-once = gsettings set org.gnome.desktop.interface color-scheme "prefer-dark"  # for GTK4 apps

exec-once = hyprpm reload

# Set power profile on startup (user preference will be preserved)
exec-once = powerprofilesctl set balanced

env = QT_QPA_PLATFORMTHEME,qt6ct  # for Qt apps

# Bindings
bindd = SUPER, code:19, Switch to workspace 10, workspace, 10
bindd = SUPER SHIFT, code:19, Move window to workspace 10, movetoworkspace, 10

# Window Rules
windowrule = match:workspace 1, match:class ^(zen|Zen|zen-.*|[Zz]en.?Browser).*
windowrule = workspace 2, match:class ^(Ghostty|ghostty|com\.mitchellh\.ghostty|dev\..*ghostty).*
windowrule = workspace 3, match:class ^(Code|code|code-oss|VSCodium)$
windowrule = workspace 3, match:class ^(Cursor).*
windowrule = workspace 7, match:class ^(google-chrome|Google-chrome|Google Chrome|chromium|Chromium)$
windowrule = workspace 7, match:class ^(zoom|Zoom|us\.zoom\.Zoom)$
windowrule = workspace 8, match:class ^(discord|Discord|vesktop|Vesktop|WebCord|ArmCord|com\.discordapp\.Discord)$
windowrule = workspace 10, match:class ^(Alacritty)$

