# Change the default Omarchy look'n'feel

# https://wiki.hyprland.org/Configuring/Variables/#general
general {
    # No gaps between windows or borders
    gaps_in = 0
    gaps_out = 1
    border_size = 1
    layout = scrolling
}

# https://wiki.hyprland.org/Configuring/Variables/#decoration
decoration {
    # Use round window corners
    # rounding = 12
}

# https://wiki.hypr.land/Configuring/Dwindle-Layout/
dwindle {
    # Avoid overly wide single-window layouts on wide screens
    # single_window_aspect_ratio = 1 1
}

# https://wiki.hypr.land/Configuring/Scrolling-Layout/
scrolling {
    # Do not wrap focus from first->last / last->first column
    wrap_focus = false
}

# Remove opacity/transparency for inactive windows
# Override default window opacity rule to keep all windows fully opaque
windowrule = opacity 1.0 override 1.0 override, match:class .*
